name: docs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package + docs deps
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[docs]"
          pip install -r docs/requirements.txt

      - name: Build Sphinx HTML
        working-directory: docs
        run: |
          python -m sphinx -T -b html -d _build/doctrees -D language=en . _build/html
